name: CI/CD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            - staging

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v2
              with:
                  node-version: '23'
            - name: Install dependencies
              run: yarn
            - name: Lint
              run: yarn lint
            - name: Build
              run: yarn build
            - name: Test
              run: yarn test
